name: PR update
on: pull_request


jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          lowercase-branch: false
          head-branch-regex: '[AIRLINE]+-\d+'
          title-template: '%headbranch%: '
          body-template: |
            Ticket: [%headbranch%](https://url/to/browse/ticket/%headbranch%)
