name: PR update
on:
  pull_request: 
    types: [opened]


jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          lowercase-branch: false
          head-branch-regex: '[airlines]+-\d+/gi'
          title-template: '%headbranch%: '
          body-template: |
            Ticket: [%headbranch%](https://url/to/browse/ticket/%headbranch%)
